[project]
name = "data-engineering-zoomcamp-2026-03-data-warehouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-api-python-client>=2.189.0",
    "google-cloud-storage>=3.9.0",
]
